### ISSUE TITLE
License == ?

### ISSUE THREAD

**Issue by guillaume-chevalier** [Vladkryvoruchko/PSPNet-Keras-tensorflow#11]
Hi, I would like to know under which license is your work available. GitHub's default license is "all rights reserved" for public repositories, such as this one.

Adding a license to your repository is simple:
https://help.github.com/articles/adding-a-license-to-a-repository/
Just be sure that in the template you pick to add your name(s).

You may also want to take a look at the following in the case you took code from this source: https://github.com/hszhao/PSPNet/blob/master/LICENSE

Many thanks!

**Comment by Vladkryvoruchko** [comment]
@guillaume-chevalier Choosed a license.)
