### ISSUE TITLE
Need the newest version

### ISSUE THREAD

**Issue by wcy940418** [Vladkryvoruchko/PSPNet-Keras-tensorflow#19]
@Vladkryvoruchko I am sorry that I push -f to the wrong repo. Do you or anybody else have the newest version so we can recover it? Thanks

**Comment by wcy940418** [comment]
@Vladkryvoruchko I think I have fixed it, please help me check if this is the correct current version. Thanks.

**Comment by Vladkryvoruchko** [comment]
@wcy940418 do you mean master branch here?

**Comment by wcy940418** [comment]
Yes, I push -f my local repo to this master, and this operation overwrote 33 commits, but then I found a way to fix it. Is there anything missing in the master branch?

**Comment by Vladkryvoruchko** [comment]
@wcy940418 at the first glance, nothing is missing, so I think everything is fine)
