### ISSUE TITLE
which are the correct EVALUATION_SCALES values

### ISSUE THREAD

**Issue by eyaler** [Vladkryvoruchko/PSPNet-Keras-tensorflow#22]
in the main code you have:
`        if args.multi_scale:
            EVALUATION_SCALES = [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]  # must be all floats!
            EVALUATION_SCALES = [0.15, 0.25, 0.5]  # must be all floats!
`
is the first one intended to be overridden by the second?

**Comment by Vladkryvoruchko** [comment]
Hello @eyaler. the first one is right. 
EVALUATION_SCALES = [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]

**Comment by jmtatsch** [comment]
First one is used by the original paper, second one works better subjectively.
