### ISSUE TITLE
Performance improvement using cv2 and numpy

### ISSUE THREAD

**Issue by karolmajek** [Vladkryvoruchko/PSPNet-Keras-tensorflow#26]
I improved performance using cv2 for reading/resizing.
I also used numpy instead of nested for in **class_image_to_image**
Here is my fork: https://github.com/karolmajek/PSPNet-Keras-tensorflow

Now I am preparing YT vid:

![img_00000203_seg_blended](https://user-images.githubusercontent.com/11379772/33152869-3b8dfa6c-cfdf-11e7-9b33-51b226d0ff61.jpg)

Do you want me to make a pull request?

**Comment by Vladkryvoruchko** [comment]
@karolmajek Please make a pull request, so I will see diff

**Comment by jmtatsch** [comment]
@karolmajek Interesting that cv2 for reading/resizing brings such a nice speedup.
And of course your class_image_to_image is much superior to mine :)
Maybe make two pull requests, one for a new flag handling a live image source and one for the class_image_to_image improvement.

**Comment by baoruxiao** [comment]
@karolmajek, thanks! Ndimage is really expensive especially for large size input image.
