### ISSUE TITLE
weights converted in wrong order

### ISSUE THREAD

**Issue by scenarios** [Vladkryvoruchko/PSPNet-Keras-tensorflow#31]
Hi @Vladkryvoruchko , I noticed  you convert the parameter of bn layer in caffe to the numpy array by the order of  'mean = v[0], variance = v[1], scale = v[2], offset = v[3]' . However, the v[0-3] actually hold the value for scale, offset, mean, variance respectively according to the caffe blob's definition in bn layer.

The reason that you can still reproduce the results is that you reverse the order again when you try to restore the parameter for the keras model from the numpy array, i.e. model.get_layer(layer.name).set_weights([mean, variance, scale, offset]).

This may not hurt when using your code completely, but it is very unexpected for those people who just use the parameter converted by the code.

Thanks for your efforts!

**Comment by jmtatsch** [comment]
@scenarios Seems like a valid point. Can you check #32? Do you have pycaffe installed to test converting the weights again?

**Comment by scenarios** [comment]
@jmtatsch Checked and everything works well now.

**Comment by jmtatsch** [comment]
@scenarios  Perfect. Would you be so kind and contribute new npy weights for the models? I don't have the whole PSPNET, pycaffe etc chain running anymore ...

**Comment by jmtatsch** [comment]
I think we can safely close this now.

**Comment by Vladkryvoruchko** [comment]
@jmtatsch yup
