### ISSUE TITLE
npy file ilnks are not working.

### ISSUE THREAD

**Issue by JustWon** [Vladkryvoruchko/PSPNet-Keras-tensorflow#34]
I found out there are three links for pre-trained weight files.

pspnet50_ade20k.npy 
pspnet101_cityscapes.npy 
pspnet101_voc2012.npy

However, only one of them are working, pspnet50_ade20k.npy.
I hope to download pspnet101_voc2012.npy file, specifically.
Can I get a link for this file?

**Comment by Vladkryvoruchko** [comment]
@JustWon Updated readme with links from @jmtatsch fork.

**Comment by xjNiu** [comment]
Where are the links for  .npy files?
