### ISSUE TITLE
'input_data' not defined in pspnet.py

### ISSUE THREAD

**Issue by chandanms** [Vladkryvoruchko/PSPNet-Keras-tensorflow#35]
I downloaded the weights and placed it in keras folder. Everything runs fine until I encounter this,
Namespace(flip=False, id='0', input_path='example_images/pascal_voc.jpg', input_size=500, model='pspnet101_cityscapes', output_path='example_results/cityscapes.jpg', weights=None)
Keras model & weights found, loading...
Predicting...
Traceback (most recent call last):
  File "pspnet.py", line 193, in <module>
    probs = pspnet.predict(cimg, args.flip)
  File "pspnet.py", line 61, in predict
    probs = self.feed_forward(img)
  File "pspnet.py", line 83, in feed_forward
    prediction = self.model.predict(np.expand_dims(input_data, 0))[0]
NameError: name 'input_data' is not defined

I checked the code and input_data variable is not defined after all. What am I missing?

**Comment by mrlzla** [comment]
The bug was occured after merging with my fork.
#36

**Comment by Vladkryvoruchko** [comment]
Fix [#2bfef37](https://github.com/Vladkryvoruchko/PSPNet-Keras-tensorflow/commit/2bfef37b69cf25f6abb0c9942286e059faa5c86e)
