### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by sunpreet007** [Vladkryvoruchko/PSPNet-Keras-tensorflow#42]
I am trying to train PSPNet on a particular dataset.
![trainingerror](https://user-images.githubusercontent.com/18732883/38073383-626455ba-3348-11e8-8ade-ac87dbcb82aa.png)
 Can someone please tell me the exact steps to be followed to train a dataset.

**Comment by Vladkryvoruchko** [comment]
Closed.
