### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by sunpreet007** [Vladkryvoruchko/PSPNet-Keras-tensorflow#44]
I am trying to train the cityscapes dataset using a small number of images. When i run the training code in the terminal although no error appears but it is not moving past the first epoch.
![screenshot from 2018-04-27 11-55-26](https://user-images.githubusercontent.com/18732883/39347765-fa201cba-4a11-11e8-8899-93ab07b59238.png)

Can someone please tell me the fix?

**Comment by Vladkryvoruchko** [comment]
@sunpreet007 did you run code on cpu?
