### ISSUE TITLE
My results: wrong colours assignment

### ISSUE THREAD

**Issue by ga84** [Vladkryvoruchko/PSPNet-Keras-tensorflow#60]
Hello and thank you for your great work!  I tried to do segmentation with this network (with cityscapes weights) and colours seem to be assigned completely wrong. Do you have an idea why this might be happening? I.e. vegetation is always blue, pavements red instead of magenta and people magenta instead of red, streets are black(static or unlabeled?) etc... Can it be that, for some reason, pixels are colourized by lowest scores? I was thinking about converting the weights myself, but I don't have pycaffe etc. installed. Could someone please upload the correct weights, after the issue with wrong order of parameters in conversion? @scenarios @karolmajek

I will post images later this evening, now I have to type from my phone and can't add pictures.

I would appreciate any suggestion what might be causing the issue. 
@wcy940418 @Vladkryvoruchko @jmtatsch 

Hier ist what I'm using:

Name                   Version                Build                     Channel

python                    3.5.5                he025d50_2    conda-forge

cudatoolkit               8.0                           4

cudnn                     6.0                           0

tensorflow                1.1.0               np112py35_0

tensorflow-gpu            1.1.0               np112py35_0

keras                     2.0.6                    py35_0    conda-forge

**Comment by Vladkryvoruchko** [comment]
@ga84 Initial image and processed are appreciated to make test on them

**Comment by jmtatsch** [comment]
@ga84 you can use my fork

**Comment by ga84** [comment]
Hello guys and thank you for your answers and great work. I solved the colours problem with some code editions from the fork of @karolmajek. 

Nevertheless here are some comparissons of my results with both of your versions. Above: @Vladkryvoruchko with karolmajek edition of parts of pspnet.py and below: @jmtatsch with sliding window predictions. Although I'd expect better results in the second case, it gives often false positives (e.g. for vegetation).

![img_20190214_112953558_seg_blended](https://user-images.githubusercontent.com/31802734/52815646-8b820c80-309f-11e9-860f-d02e4fff0386.jpg)

![img_20190214_112953558_seg_blended_withsliding](https://user-images.githubusercontent.com/31802734/52815668-989efb80-309f-11e9-82f5-e05f7fed57ba.jpg)

___
![berlin_000032_000019_leftimg8bit_seg_blended](https://user-images.githubusercontent.com/31802734/52815682-9dfc4600-309f-11e9-9fde-1dd1f707105c.png)

![berlin_000032_000019_seg_blended_withsliding](https://user-images.githubusercontent.com/31802734/52815694-a3599080-309f-11e9-8344-4d1d231a2c60.png)
___
![lindau_000003_000019_leftimg8bit_seg_blended](https://user-images.githubusercontent.com/31802734/52815717-b10f1600-309f-11e9-9ec8-4670023668ed.png)

![lindau_000003_000019_seg_blended_withsliding](https://user-images.githubusercontent.com/31802734/52815725-b5d3ca00-309f-11e9-9ba1-94455fab2331.png)

**Comment by jmtatsch** [comment]
@ga84 wow, those are crazy quality differences.

So you have just taken @karolmajek s PR? everything else default? As far as I can remember he has only changed a couple of pillow IO and resize functions to opencv, which greatly increased the speed.
Maybe some pillow functions have changed whereas the opencv ones stayed the same?

Concerning the sliding window predictions with my fork, you seem to have made the windows too small. The network has too little context then to discern between street, vegetation and building.

**Comment by ga84** [comment]
@jmtatsch  yes, I used karolmajek's version, where he applied cv2 for image reading and resizing in prediction. Also the differences are class_image_to_image and color_class_image_slow. Actually no PIL functions as far as I can see, if that's what you mean?

Good point about the window size, I hope I would've come to that eventually myself xD. The results are not that bad without it though. I can post some updates on Tuesday, with varying window size. 

Thanks for answering!
