### ISSUE TITLE
"Image not found" error

### ISSUE THREAD

**Issue by mhkeller** [Vladkryvoruchko/PSPNet-Keras-tensorflow#68]
Hi, I am trying to get this running but I'm getting a `Reason: Image not found` error.

1. I created a virtualenv running python 3.6.6
2. I ran `pip install -r requirements.txt --upgrade`
3. I downloaded the weights and put them in the `weights/keras` dir
4. I ran `python pspnet.py -m pspnet101_voc2012 -i example_images/pascal_voc.jpg -o example_results/pascal_voc.jpg`

The image `pascal_voc.jpg` is in that that directory so I'm not sure why it can't find that image.

The console output I get is `Using TensorFlow backend.` and then it seems to fail when it imports keras
```
  File "pspnet.py", line 8, in <module>
    from keras import backend as K
```

It also says

```
Reason: image not found


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems
```

Do i need to do other installation steps other than pip installing the dependencies?

**Comment by jmtatsch** [comment]
Tensorflow is not working properly. Possibly something with your library path.

**Comment by mhkeller** [comment]
Thanks. Yep I didn't understand how to hook up that dependency.
