### ISSUE TITLE
--ms and -s flags not implemented?

### ISSUE THREAD

**Issue by mhkeller** [Vladkryvoruchko/PSPNet-Keras-tensorflow#69]
In the readme, it says you can use the `-ms` and `-s` flags [but these don't seem to be implemented](https://github.com/Vladkryvoruchko/PSPNet-Keras-tensorflow/blob/ff38556e64d62dc992b2edaa3b07a7e24b6323ef/pspnet.py#L145-L160) and if you use them, you get an error saying as much.

Is it possible to use these options through the CLI?

**Comment by raghuram-kukun** [comment]
@mhkeller Same issue here. Were you able to fix this?

**Comment by raghuram-kukun** [comment]
@mhkeller The function to use these arguments are there, we just need to make a call to these functions if the arguments to multi-scale and sliding window are True.

**Comment by Vladkryvoruchko** [comment]
See https://github.com/Vladkryvoruchko/PSPNet-Keras-tensorflow/pull/72
