### ISSUE TITLE
Cityscapes weights

### ISSUE THREAD

**Issue by jmtatsch** [Vladkryvoruchko/PSPNet-Keras-tensorflow#9]
Hi Vlad,

I am trying to convert the original pspnet101_cityscapes weights from https://github.com/hszhao/PSPNet to keras.

`python weight_converter.py pspnet101_cityscapes_713.prototxt pspnet101_cityscapes.caffemodel`

In PSPNet-Keras-tensorflow I adjusted: 
```
WEIGHTS = 'pspnet101_cityscapes.npy'
DATA_MEAN = np.array([[[72.78044, 83.21195, 73.45286]]]) # RGB
x = Conv2D(19, (1, 1), strides=(1, 1), name="conv6")(x) # changed the classes from 150 to 19 
```
PSPNet runs through without errors, unfortunately, the output for a test image remains indiscernible:

![test](https://user-images.githubusercontent.com/3080674/29361099-52eb370c-8286-11e7-8274-ceb4895fe0b9.png)
![out](https://user-images.githubusercontent.com/3080674/29361101-54c3c2ce-8286-11e7-8beb-9ab3c1022cf3.png)

Do you have an idea what I could be missing?

**Comment by jmtatsch** [comment]
Changed back the means to the default as apparently pspnet did not use different means when training on different datasets, but still: 

![test](https://user-images.githubusercontent.com/3080674/29364178-ec109420-8292-11e7-8cb8-3b2b7adff94d.jpg)

**Comment by hujh14** [comment]
The architecture for pspnet101_cityscapes_713.prototxt is different from the one specified in layers_builder.py. To load those weights, you need to convert that model into keras.

**Comment by jmtatsch** [comment]
@hujh14 thank you so much for figuring this out. It seems to work now :)
![test3](https://user-images.githubusercontent.com/3080674/29413266-10c9646c-835c-11e7-96df-9b6150e6c8ee.jpg)
![blended](https://user-images.githubusercontent.com/3080674/29413260-0af8d1b2-835c-11e7-805c-4d9d9d22e2e7.jpg)
I will open a pull request later..

**Comment by jmtatsch** [comment]
#10

**Comment by hellochick** [comment]
@hujh14 Hey, Could you tell me the difference between directly load weight and load model to keras first?
Since I want to re-implement PSPNet in pure tf for research, but I got bad result on it.

Thanks!!

**Comment by jmtatsch** [comment]
@hellochick the original authors used a deeper 101 layer resnet in their pspnet for cityscapes. My mistake was that i tried to convert the weights of a 101 layer network to a 50 layer architecture. Of course the architecture needed a deeper resnet also.

**Comment by hellochick** [comment]
@jmtatsch Thank you for answering, I got it. I try to turn your model into tensorflow, but the result didn't meet my expectation:
![test](https://user-images.githubusercontent.com/18046598/31770459-9444afa6-b50a-11e7-90de-59dab09ebc16.png)
Do you have any idea about the strange result ( Since most of part are predicted correctly except the trees and buildings ) ? 
Or is there any difference between keras and tf operations ?

Thank you a lot !

**Comment by jmtatsch** [comment]
@hellochick can you also edit in the original image above? It definitely has more trouble with the trees than I would expect. I am also still missing 1.7% to reproduce the published results. Could also be the preprocessing/interpolation that is different in a matlab/caffe pipeline.

**Comment by hellochick** [comment]
@jmtatsch Hey, here is the origin image:
![test](https://user-images.githubusercontent.com/18046598/31774834-728b5afe-b519-11e7-90c9-c1f946f4877d.png)
And following image is result produced by your model
![test_out_seg](https://user-images.githubusercontent.com/18046598/31775393-1661c842-b51b-11e7-8786-4705c29f6363.png)
It looks perfect
